### ISSUE TITLE
Issues on Metacells Installation(Win10)

### ISSUE THREAD

**Issue by XiangyangWang296** [tanaylab/metacells#2]
Hi
Thanks for bringing Metacell into python3, for it's more convenient on saving computing sources while treating huge dataset.
I would like to install metacells but I meet some problem. It's great if you could help me.
At start I tried to use conda to complete installation but there is no conda packages. Then I prepared C++ visual studio required as manual, and use pip(upgraded to the newest version)  to install metacells, but a lot problems emerged when 'pip install metacells' started. The following is the summary of error list (list in order) that can be useful informations for you:
1.  Building wheel for metacells (setup.py) ... error
2.  ERROR: Command errored out with exit status 1: ......
3.  error: command 'C:\\Program Files (x86)\\Microsoft Visual Studio 14.0\\VC\\BIN\\x86_amd64\\cl.exe' failed with exit status 2
4.  ERROR: Failed building wheel for metacells
5.  error: command 'C:\\Program Files (x86)\\Microsoft Visual Studio 14.0\\VC\\BIN\\x86_amd64\\cl.exe' failed with exit status 2

Hope to receive your reply. 
Metacells COME ON!

**Comment by orenbenkiki** [comment]
We haven't officially published the package yet. I'm happy to hear people are eager to use it!

We are still finalizing some internal details - **do not use this version** except for just playing with the framework and APIs.

Also, note that for large data sets, while this package is much, much faster than the old R code, it is still a memory and CPU hungry beast. In particular, it uses all the CPU cores on your machine in parallel to reduce overall run-time. Therefore, for large data sets, I wouldn't run it on a laptop or a modest desktop, but rather on a proper server, which typically means Linux.

We've therefore only installed this on Linux so far. Given it contains a C++ extension, it is to be expected that installing it on Windows will not "just work" because, well, Windows. I'll definitely ensure that it is installable on Windows when we officially publish it. Probably would need to worry about MacOS as well...

We expect to publish it "soon" - within a few weeks - I'll keep this issue open and update it when we do.

**Comment by orenbenkiki** [comment]
Turns out the current implementation strategy of metacells is not supported by (native) Windows. Specifically metacells requires the `fork` parallelism which is only supported on Linux and MacOS.

Fixing this would require a major change in the implementation of metacells, Python, or Windows. Neither seems likely in the foreseeable future. Sorry :-(

All is not _quite_ lost though. Running metacells on a Windows machine is still possible, by installing [WSL (Windows Subsystem for Linux)](https://docs.microsoft.com/en-us/windows/wsl/) and installing and running metacells within it.
