### ISSUE TITLE
To get MC object with a single-cell layer

### ISSUE THREAD

**Issue by UboCA** [tanaylab/metacells#40]
Dear tanaylab-team,

I'm a new player in metacell python package(mc2). mc2 could be a very unique and effective tool in my work.

After a first run on my data, mc2 merge homogeneous single cells into a pseudo-bulk cell, I tried to project pre-existing annotation into MCs

1) one way could be naming a MC by the major cell type(if cell type is well related to MCs);

2) or using pie to display precise contribution of cell types for per single MC plot).

3) re-forming sc-layers maybe by `[mcell_mc2d_force_knn_on_cells](https://tanaylab.github.io/metacell/reference/mcell_mc2d_force_knn_on_cells.html)`
Just like ways in metacell R, mc, mc2d,  are produced to plot 2d plot in sc/mc level.

To better visualiaze data, I am prone to using **3)**, but wonder if there is any other way to create single-cell layers on mc2.metacell object. Could you give me any directions about it ?

Best

**Comment by orenbenkiki** [comment]
I'm not quite sure what you mean by "create single-cell layers on mc2.metacell object".

AnnData is restricted in that you can't have both per-cell and per-metacell data in the same object (this is why we are working on DAF to replace it in some future version).

So:

When you compute metacells you end up with a new AnnData object where each observation is a metacell.

You still have the original AnnData object where each observation is a cell. There's a per-cell "metacell" property that gives the 0-based index of the metacell the cell belongs to (or negative if it is an outlier).

Yes, if you have a per-cell type annotation, you can use a majority rule to assign a type to the metacells. Ot compute for each type the fraction of the cells of that it contains. All these give you per-metacell data (that would live in the metacells AnnData object).

Visualizing this can be done in any way you want (you can access AnnData objects from R if that is easier).

**Comment by UboCA** [comment]
Thanks for sharing key points. 
Yes, AnnData doesn't allow both per-cell and per-metacell data in the same object, so now I will try to get it in other ways.
And expected to see DAF updates in the future version.

**Comment by UboCA** [comment]
Hi, Oren @orenbenkiki 

I have another question maybe not be an issue (So put here as a discussion)

Will output be different if we feed metacells raw data or normalized data (like 10000 count per cell)?
Does metacells normalized data in its pipeline?
Since normalized data will lose some useful info for downstream analysis (like smaller cell has less umi that can be captured).

Best 
Xiangyang

**Comment by orenbenkiki** [comment]
"It's complicated".

In v0.8 (which I assume you run) we provide UMI counts per gene per metacell so each is sort-of the sum of the gene's UMIs in all the cells in the metacell. It isn't exactly that because we renormalize some cells to avoid having a single very large cell to dominate the metacell. This lead to fractional UMIs which people found to be confusing.

After gaining experience with the system, in v0.9 (the next upcoming release) we change things (this is described in detail in the main [README](https://github.com/tanaylab/metacells) of the package). Basically, we do provide the exact total UMIs of the cells of each gene in each metacell. We also provide the total UMIs of all the genes of all the cells per metacell.

**But**, we don't use (or recommend using) this to determine the gene expression level in the metacell.

Instead we provide a fraction of the gene out of the total UMIs (that is, a normalized gene expression level), which is corrected in various ways to give a better estimate (we are finalizing this right now as part of the upcoming 0.9 release). So if you multiply the total-UMIs-per-metacell with the fraction-of-the-gene-out-of-the-total you will not get the total-UMIs-of-the-gene-in-the-cells-of-the-metells.

This turns out to be "better" in various ways. For example, it puts things in a single uniform scale making it easier to analyze and compare values between metacells regardless of metacell depth; we can provide a "better" estimator; people aren't thrown off by having magical fractional pseudo-UMIs.

But you still get the UMIs count for the cases it matters - for example, when we compute fold factors between gene expressions, we ignore as "insignificant" any cases where the total number of UMIs involved is less than some threshold (by default 40). This cleans up a cases where a lowly expressed gene has 1 UMIs in one metacell and, say, 20 UMIs in another - one can't seriously say we have a 20x ratio in gene expression in such a case (extremely weak gene). It is better to say "just ignore this as insignificant".

You can take your v0.8 metacells and convert them to 0.9 format using a script we provide (see the README). This is still WIP, YMMV, etc.

**Comment by UboCA** [comment]
> Body
Yes, now I run metacells v0.8. And I will try to handle v0.9 based on your description and the README. Thanks for your detailed experience.
