### ISSUE TITLE
AssertionError, but not sure why

### ISSUE THREAD

**Issue by hurleyLi** [tanaylab/metacells#7]
Hi,
I had this assertion error when I run `mc.pl.relate_genes(clean)`

```
/opt/conda/lib/python3.8/site-packages/metacells/utilities/annotation.py in set_vo_data(adata, name, data, formatter)
   1158     utl.log_set(adata, 'vo', name, data, formatter=formatter)
   1159 
-> 1160     utt.mustbe_canonical(data)
   1161     if not utt.frozen(data):
   1162         utt.freeze(data)

/opt/conda/lib/python3.8/site-packages/metacells/utilities/typing.py in mustbe_canonical(shaped)
    918 
    919     if hasattr(sparse, 'has_canonical_format'):
--> 920         assert getattr(sparse, 'has_canonical_format'), \
    921             'non-canonical sparse matrix: might have duplicate indices'
    922 

AssertionError: non-canonical sparse matrix: might have duplicate indices
```

I double checked that neither .obs or .var have duplicated indexes. Could you please let me know how the program determine whether my AnnData have duplicated indices? Also if I comment out `utt.mustbe_canonical(data)`, things seems to work fine...

Thanks!

**Comment by orenbenkiki** [comment]
It couldn't be in `.obs` or `.var` - note it is in `get_vo_data` (per-var-per-obs data, as in per-gene-per-cell data) so it either the `.X` or one of the `.layers`. You could also tell this is the case because it is talking about a matrix and all of `.obs` and `.var` are vectors.

Most likely you have created your overall matrix by some operations such as concatenation of sub-matrices and didn't ensure the result is in canonical format.

**Comment by tzeitim** [comment]
I am facing the same issue here and, indeed, I am concatenating a bunch of matrices using some sort of :

```
adata.concatenate(adata1, adata2)
```

Could you please provide a bit more information on how to ensure the result of such concatenation is canonical? What exactly this it mean?

Thanks!

**Comment by orenbenkiki** [comment]
* You concatenated some matrices data.
* The matrices data was in a sparse format.
* Scipy in its finite wisdom doesn't figure out that if each of the concatenated matrices were canonical, the result is canonical.
* Canonical data has no duplicate indices, and has sorted indices, as is documented in the `is_canonical` function.
* Therefore the result is marked as non-canonical (possibly has duplicate indices, possibly has unsorted indices).
* Therefore you need to to something to make the data canonical.
* For which there are scipy functions `sum_duplicates` and `sort_indices`, which you can invoke directly from scipy or if you find it easier, using the MC2 wrappers with the same name.
* You need to do this before you access the data using MC2, otherwise MC2 will complain the data is not canonical, which it did, and rightly so.

**Comment by tzeitim** [comment]
Great. This is very helpful.

I would have expected that the anndata functionality for concatenation makes sure that all these technical details are taken care of.

Thanks for all the pointers.
