### ISSUE TITLE
ctx pyscenic Error

### ISSUE THREAD

**Issue by angelica-varesi** [tanaylab/metacells#71]
Hi, 
I am trying to compute the Cistarget step of pyscenic after obtaining meta cells with the metacell2 pipeline and then the GRN with arboreta package and saved in a tsv file. However, I keep obtaining
the same error, which refers to not finding the file or directory even if all the files are present and exist in the specified locations. 
Could you please help me in fixing this code? 

'''
pyscenic ctx /../PY_SCENIC/TRIAL_PY/Trial_meta_adj.tsv \
    /../hg38__refseq-r80__10kb_up_and_down_tss.genes_vs_motifs.rankings.feather /../hg38__refseq-r80__500bp_up_and_100bp_down_tss.genes_vs_motifs.rankings.feather \
    --annotations_fname /../motifs-v9-nr.hgnc-m0.001-o0.0.tbl \
    --expression_mtx_fname /../Trial_counts_RNA_metacell_raw_log1p.csv \
    --output /../Trial_meta_reg.csv \
    --mask_dropouts \
    --num_workers 10
'''

: No such file or directory

Thanks a lot to whoever helps!
Angelica

**Comment by orenbenkiki** [comment]
It probably has nothing to do with MC2. Off the top of my head, the path of the files seems wrong; `/../whatever` is an absolute path saying "go to the root of the file system, then go one level up, then go down to `whatever`. This path makes no sense since there's nothing "above" the root of the file system.
