### ISSUE TITLE
Working with muptiple samples from different conditions

### ISSUE THREAD

**Issue by onurcanbektas** [tanaylab/metacells#76]
When working with samples from multiple conditions, what is the recommended procedure in terms of integration?
Should the metacell calculation should be done on all sample (possibly from multiple conditions), or the metacells of individual samples be calculated, and then the resulting metacells be "integrated"?

**Comment by orenbenkiki** [comment]
Ideally, you should run metacells on the union of the data sets. This gives the algorithm the best chance to isolate rare cell states.

If you see metacells that contain a good mix of the batches, then life is good. However, often there are problems.

If you see metacells that contain cells from only a subset (or even just one) batch, you need to investigate whether this is due to the batch really containing different cell states, or whether this is due to a technical batch effect that needs to be corrected.

If you are using MCView, the marker heatmap is always a good place to start. Doing gene-gene plots and then differentail expression of metacells which "should" be very similar but have different batch signatures is a more focused approach.

If you do detect technical batch effects, you will need to correct the situation; the metacells package doesn't contain tools for batch effect correction - there are too many options. What you can do is exclude the genes (if they are very few) or mark them as lateral (which only helps up to a point).

Depending on your situation, this issue can range from not being one, to being easily resolved, to having a really bad time. There's no silver bullet I know of to solve this problem in general.
