### ISSUE TITLE
question about divide_and_conquer_pipeline

### ISSUE THREAD

**Issue by CCCBBG** [tanaylab/metacells#78]
Excuse me. May I have a question about divide_and_conquer_pipeline？
This is my code and results.Is this code or result reasonable?
>>> metacell_results = mc.pipeline.divide_and_conquer_pipeline(
...     adata, 
...     # target_metacell_size=40,
...     target_metacell_umis=160000,
...     random_seed=123456
... )
set unnamed.var[selected_gene]: * -> False
set unnamed.var[rare_gene]: 0 true (0%) out of 36601 bools
set unnamed.var[rare_gene_module]: 36601 int32 elements with all outliers (100%)
set unnamed.obs[cells_rare_gene_module]: 45116 int32 elements with all outliers (100%)
set unnamed.obs[rare_cell]: 0 true (0%) out of 45116 bools
set unnamed.var[selected_gene]: 6159 true (16.83%) out of 36601 bools
set unnamed.obs[metacell]: 45116 int32s
set unnamed.obs[dissolved]: 0 true (0%) out of 45116 bools
set unnamed.obs[metacell_level]: 45116 int32s

Why is it displaying "set unnamed.obs[metacell]: 45116 int32s"?
Is there any manuscript or similar reference available?
Thank you very much for your software. I am really looking forward to hearing back from you.

**Comment by CCCBBG** [comment]
Vignettes I mean

**Comment by orenbenkiki** [comment]
It means there is a per-cell property saying which metacell each cell belongs to. SInce you have 45K cells the length of this data is 45K entries, each is an int32s.

https://github.com/tanaylab/metacells-vignettes

**Comment by CCCBBG** [comment]
Thanks a lot！
Have a good day！

**Comment by CCCBBG** [comment]
Excuse me. May I have a annother question about the result of mc.pl.collect_metacells.Especially the grouped column
print(metacells.obs.head(3))
       grouped  __zeros_downsample_umis  ...  
M0.81       24                     1864  ...                      
M1.74       31                      689  ...                     
M2.10       26                     1265  ...                      

Is there any connection between this row name "M0.81" and "grouped 24"? How should we understand this?

 I am looking forward to your reply

**Comment by orenbenkiki** [comment]
M0.81 is the name of the metacell. This is metacell #0 and the .81 suffix is a small hash of the indices of the cells it contains. This ensures that when you recompute metacells, the names won't match, so applying per-metacell data from the wrong set of metacells will fail.

24 is the number of cells in the metacell.

And so on. You can see the docs https://github.com/tanaylab/metacells?tab=readme-ov-file#metacells-computation for what the different columns mean.

**Comment by CCCBBG** [comment]
Excuse me. May I have a annother question about the number of Metacells.I realized that the default of target_metacell_size and target_metacell_umis.But how could I find the optimal target_metacell_umis using my own data?

**Comment by orenbenkiki** [comment]
"Optimal"...

The goal of MCs is to capture cell states with sufficient fidelity to robustly estimate gene expression levels. Since individual cells are very sparse and very noisy this requires "many" cells and "many" UMIs. The defaults are reasonable to ensure the MCs are robust estimators, given current scRNA-seq technologies (e.g., 10X) with typical sequencing depth, and given you have "enough" cells in the data set.

Tweaking the targets is useful in two cases; either you have cells with higher UMIs per cell than normal, so you can reduce the target cells per MC; or you have a very small data set and you understand that getting a robust estimate of cell states just isn't possible, so you reduce the targets to avoid getting MCs which span multiple cell states - at the cost of getting less reliable results. Both should be done with great care and by examining the results and applying prior biological knowledge.

We are working on advanced QC measures that will help isolate which MC s are "sufficiently sampled" and which MCs aren't (that is, which cell states just don't have enough data in the original data set to be as robustly estimated). This is WIP. For now, you have to look at the results and apply your knowledge as a biologist and some common sense...

**Comment by CCCBBG** [comment]
Thank you very much for your reply. In my sequencing data, the median ncounts is significantly lower than typical single-cell transcriptome sequencing from the 10x platform. Therefore, I would like to explore the optimal target_metacell_umis. I'm wondering if it would be possible to identify the optimal target_metacell_umis by running multiple iterations and analyzing the distribution or correlation patterns of the resulting metacells.

**Comment by orenbenkiki** [comment]
How low is your UMIs count per cell? You may want to increase the target metacell size (in cells) so that on average that would bring you to the target metacell UMIs (160K which is a reasonable number). If your data set is small, you could instead reduce the target metacell UMIs but that comes at the cost of degrading the quality of the result.

**Comment by CCCBBG** [comment]
Excuse me. May I have a annother question about the batch effect.
I observed significant batch effects after dimensionality reduction and clustering of approximately 2,000 metacells. Would it be feasible to perform batch correction prior to metacell construction? The tutorial demonstrates metacell generation using UMI counts. Does this indicate that the metacells algorithm is better suited for single-cell datasets with minimal batch effects?

**Comment by orenbenkiki** [comment]
The metacells algorithm assumes that, if there are batch effects, you have excluded the affected genes (not that common), or corrected them (using some method) before computing the metacells, or at least marked them as lateral. There's no batch correction built into the algorithm as the decision of which gene differences are "batch effects" and which are "true differences" is impossible to make without supervision.
