### ISSUE TITLE
output array is read-only after running .divide_and_conquer_pipeline

### ISSUE THREAD

**Issue by hurleyLi** [tanaylab/metacells#9]
Hi!
I'd like to normalize my AnnData using the Scanpy pipeline after running Metacells on the raw counts, so that I can analyze MC and single-cells in parallel. However, after running `.divide_and_conquer_pipeline`, the count matrix in `.X` seem to become read-only:

```
ValueError                                Traceback (most recent call last)
<ipython-input-53-d7471aab34d4> in <module>
----> 1 sc.pp.normalize_total(clean)

/opt/conda/lib/python3.8/site-packages/scanpy/preprocessing/_normalization.py in normalize_total(adata, target_sum, exclude_highly_expressed, max_fraction, key_added, layer, layers, layer_norm, inplace, copy)
    186             adata.obs[key_added] = counts_per_cell
    187         _set_obs_rep(
--> 188             adata, _normalize_data(X, counts_per_cell, target_sum), layer=layer
    189         )
    190     else:

/opt/conda/lib/python3.8/site-packages/scanpy/preprocessing/_normalization.py in _normalize_data(X, counts, after, copy)
     24         sparsefuncs.inplace_row_scale(X, 1 / counts)
     25     else:
---> 26         np.divide(X, counts[:, None], out=X)
     27     return X
     28 

ValueError: output array is read-only
```

If I run an extra `clean.X = clean.X.copy()`, it fixed the issue. But just wondering if you could make the output matrix of Metacells not read-only. 

Thanks!
Hurley

**Comment by hurleyLi** [comment]
Also I just found that the `mc.pl.collect_metacells()` function also makes the __input__ AnnData count matrix read-only.

**Comment by orenbenkiki** [comment]
In general MC2 assumes and enforces that the AnnData is read-only because it aggressively caches computed intermediates (e.g. sums, variances etc.) of the arrays and matrices for improved performance. Directly modifying any array or matrix that was used in the computation will silently invalidate all such cached data and will cause mysteriously incorrect results.

In general the expected behavior is that if you want different data, put it in a different name. This ensures all processing steps are unambiguos and give the same results regardless of the order they are executed. This is not true if you modify the values in-place, so this can lead to subtle bugs regardless of caching.

So, the MC2 code makes the tradeoff is that it is better to get an error when trying to modify the data rather than getting mysteriously incorrect results, and having to repeat common intermediate computations. The end result is clearer, safer and faster code.

Note that AnnData is perfectly happy to keep multiple 2D matrices (they call them "layers"). Personally I think they made a serious API usability mistake in making `X` a special entity which is almost exactly, but not quite, a normal "layer". This encourages modifying X and other attributes in-place, potentially leading to subtle bugs. IMO they should have made X to be just a layer and possibly introduced a notion of "default layer name" or something like that.

In contrast the `set_vo_data` and `get_vo_data`  function don't make X special - you always give an explicit name (X has the name `__x__`). All the MC2 annotation access methods aggressively enforce that the data is read-only to ensure the speed and safery advantages described above.

So - if you, say, want to work on the fraction-of-gene-UMIs-in-each cell instead of the count-of-gene-UMIs-in-each cell, you should create a different layer called `UMI_fractions` (for example).

That said, if you want to take the safeties off, you can use the `unfreeze` function. At least you'd have to be explicit about it ("explicit is better than implicit" and all that).
